import type { NextPage } from 'next'
import style from './index.module.scss'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import classNames from 'classnames'
import Image from 'next/image'
import CoordinateSelector from '../../../components/CoordinateSelector'
import { useState } from 'react'
import { TextField } from '@mui/material'
import api from '../../../api'

const MarketMapContainer = dynamic(
  () => import('../../../components/MapContainer/MarketCompareMap'),
  { ssr: false }
)

const AprRegion: NextPage = () => {
  const [longitude, setlongitude] = useState<number | null>(null)
  const [latitude, setlatitude] = useState<number | null>(null)
  const [locatedCounty, setlocatedCounty] = useState<string | null>(null)
  const [locatedTown, setlocatedTown] = useState<string | null>(null)
  const [isSelectorActive, setisCoordinateSelectorActive] = useState<boolean>(false)

  const handleCoordinateSelect = async (longitude: number, latitude: number) => {
    setlongitude(longitude)
    setlatitude(latitude)
    setisCoordinateSelectorActive(false)
    const { statusCode, responseContent } = await api.prod.getCountyTownNameByCoordinate(longitude, latitude)
    if (statusCode === 200) {
      setlocatedCounty(responseContent.countyname)
      setlocatedTown(responseContent.townname)
    } else {
      setlocatedCounty(null)
      setlocatedTown(null)
    }
  }

  return (
    <>
      <Head>
        <title>VPMC | 實價登錄資訊平台</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/yuantai.ico" />
      </Head>
      <div className={style.main}>

        <div className={style.panel}>

          <div className={style.filterGroup}>

            <div className={classNames({
              [style.filterSection]: true,
              [style.divide]: true
            })}>
              <CoordinateSelector
                longitude={longitude}
                latitude={latitude}
                locatedCounty={locatedCounty}
                locatedTown={locatedTown}
                active={isSelectorActive}
                onClick={() => {
                  setisCoordinateSelectorActive(prev => !prev)
                }}
              />
            </div>

            <div className={classNames({
              [style.filterSection]: true,
              [style.divide]: true
            })}>
              <TextField
                size='small'
              ></TextField>
            </div>

            <div className={style.searchBtn}
            >
              <Image src={'/aprRegion/search.png'} width='30px' height='30px' />
              <p>查詢</p>
            </div>

          </div>

          <div className={style.graphGroup}>
          </div>

        </div>

        <div className={style.content}>
          <div className={style.mapContainer}>
            <MarketMapContainer
              active={isSelectorActive}
              onCoordinateSelect={handleCoordinateSelect}
            />
          </div>
        </div>

      </div>
    </>
  )
}

export default AprRegion
