import type { NextPage } from 'next'
import style from './index.module.scss'
import dynamic from 'next/dynamic'
import Head from 'next/head'

const MarketMapContainer = dynamic(
  () => import('../../../components/MapContainer/MarketCompareMap'),
  { ssr: false }
)

const AprRegion: NextPage = () => {

  return (
    <>
      <Head>
        <title>VPMC | 實價登錄資訊平台</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/yuantai.ico" />
      </Head>
      <div className={style.main}>

        <div className={style.panel}>

          <div className={style.filterGroup}>

            {/* <CountySelector
              countyData={aprRegionInfo.countyData!}
              selectedCounty={aprRegionInfo.county}
              onCountyChange={(county) => {
                dispatch(
                  initAprRegionCounty(county)
                )
                reFetchTownData(county)
              }}
            />

            <TownSelector
              townData={aprRegionInfo.townData!}
              selectedTown={aprRegionInfo.town}
              onTownChange={(town) => {
                dispatch(
                  initAprRegionTown(town)
                )
              }}
            />

            <div className={style.searchBtn}
              onClick={() => {
                handleSearch()
              }}
            >
              <Image src={'/aprRegion/search.png'} width='30px' height='30px' />
              <p>查詢</p>
            </div> */}
          </div>

          <div className={style.graphGroup}>
            {/* {
              aprRegionInfo.displayData
                ? <TabsPanel
                  displayData={aprRegionInfo.displayData}
                ></TabsPanel>
                : <></>
            } */}
          </div>

        </div>

        <div className={style.content}>
          <div className={style.mapContainer}>
            <MarketMapContainer
              basemap='gray'
            />
          </div>
        </div>

      </div>
    </>
  )
}

export default AprRegion
