import React from 'react'
import type { NextPage } from 'next'
import WithNavProtected from '../../../layout/front-layout/WithNavProtected'
import Head from 'next/head'
import MarketCompareContainer from '../../../containers/MarketCompareContainer'

const MarketCompare: NextPage = () => {
  return (
    <>
      <Head>
        <title>VPMC | 實價登錄資訊平台</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/yuantai.ico" />
      </Head>
      <MarketCompareContainer />
    </>
  )
}

export default WithNavProtected(MarketCompare)
