import type { NextPage } from 'next'
import style from './index.module.scss'
import Drawer from '../../components/Drawer'
import { useState } from 'react'
import Head from 'next/head'
import dynamic from 'next/dynamic'
import CommiteeCard from '../../components/CommiteeCard'

const MapContainer = dynamic(
  () => import('../../components/MapContainer/EsriMap'),
  { ssr: false }
)

const AprV2: NextPage = () => {
  const [first, setfirst] = useState<boolean>(false)
  return (
    <>
      <Head>
        <title>VPMC | 實價登錄資訊平台</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/yuantai.ico" />
        <link rel="stylesheet" href="https://js.arcgis.com/4.23/@arcgis/core/assets/esri/themes/light/main.css" />

      </Head>
      <div className={style.main}>
        <Drawer
          open={first}
          onClose={() => { setfirst(false) }}
        >
          <CommiteeCard />
          <CommiteeCard />
          <CommiteeCard />
          <CommiteeCard />
          <CommiteeCard />
          <CommiteeCard />
          <CommiteeCard />
          <CommiteeCard />
          <CommiteeCard />
          <CommiteeCard />
          <CommiteeCard />
          <CommiteeCard />
          <CommiteeCard />
          <CommiteeCard />
          <CommiteeCard />

        </Drawer>
        <div className={style.content}>
          <button
            className={style.drawerBtn}
            onClick={() => { setfirst(prev => !prev) }}
          >open</button>
          <MapContainer basemap='gray' />
        </div>
      </div>
    </>
  )
}

export default AprV2
