import type { NextPage } from 'next'
import style from './index.module.scss'
import Drawer from '../../components/Drawer'
import { useState } from 'react'
import Head from 'next/head'
import dynamic from 'next/dynamic'
import CommiteeCard from '../../components/CommiteeCard'
import Image from 'next/image'
import doubleRight from '../../public/aprV2/doubleRight.png'
import doubleLeft from '../../public/aprV2/doubleLeft.png'
import doubleRightHover from '../../public/aprV2/doubleRight-hover.png'
import doubleLeftHover from '../../public/aprV2/doubleLeft-hover.png'
import { useSelector } from 'react-redux'
import { selectCommitee } from '../../store/slice/commitee'
import { square } from '../../components/MapContainer/AprV2Map'
import { parseCommitee } from '../../lib/parseCommitee'

const MapContainer = dynamic(
  () => import('../../components/MapContainer/AprV2Map'),
  { ssr: false }
)

const AprV2: NextPage = () => {
  const commiteeInfo = useSelector(selectCommitee)
  const [first, setfirst] = useState<boolean>(false)
  const [drawerBtn, setdrawerBtn] = useState<string>(doubleRight.src)
  return (
    <>
      <Head>
        <title>VPMC | 實價登錄資訊平台</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/yuantai.ico" />
        <link rel="stylesheet" href="https://js.arcgis.com/4.23/@arcgis/core/assets/esri/themes/light/main.css" />

      </Head>
      <div className={style.main}>
        <Drawer
          open={first}
          onClose={() => { setfirst(false) }}
        >
          {
            commiteeInfo.commiteeInExtent.map((commitee, index) => {
              const unitPrice = Math.round(Number(commitee.value?.avg_unit_price) * square / 1000) / 10
              if (unitPrice !== 0) {
                // return <></>
                return <CommiteeCard key={index}
                  id={commitee.id}
                  unitPrice={unitPrice}
                  commiteeName={parseCommitee(commitee.organization)}
                  buildingType={commitee.value?.building_type!}
                  address={commitee.address}
                  completionDate={commitee.value?.completion_date!}
                  aprCount={commitee.value?.apr_count!}
                />
              } else {
                return <></>
              }
            })
          }

        </Drawer>
        <div className={style.content}>

          <div className={style.mapContainer}>
            <MapContainer basemap='gray' />
          </div>

          <div className={style.footer}>
            <Image
              className={style.drawerBtn}
              src={drawerBtn} width='30px' height='30px'
              onMouseMove={() => {
                if (!first) {
                  setdrawerBtn(doubleRightHover.src)
                } else {
                  setdrawerBtn(doubleLeftHover.src)
                }
              }}
              onMouseLeave={() => {
                if (!first) {
                  setdrawerBtn(doubleRight.src)
                } else {
                  setdrawerBtn(doubleLeft.src)
                }
              }}
              onClick={() => {
                setfirst(prev => !prev)
                // setdrawerBtn(doubleLeft.src)
                if (!first) {
                  setdrawerBtn(doubleLeft.src)
                } else {
                  setdrawerBtn(doubleRight.src)
                }
              }}
            />
          </div>

        </div>
      </div>
    </>
  )
}

export default AprV2
