import type { NextPage } from 'next'
import { useRouter } from 'next/router'
import Head from 'next/head'
import { ParsedUrlQuery } from 'querystring'
import { GetServerSideProps } from 'next'
import dynamic from 'next/dynamic'
import Image from 'next/image'
import style from './index.module.scss'

interface ICommiteeDetail {
  title: string
}

interface IProps {
  commiteeDetail: ICommiteeDetail
}

interface Params extends ParsedUrlQuery {
  id: string
}

export const getServerSideProps: GetServerSideProps<IProps, Params> = async ({
  params,
}) => {
  // const api = `http://asia-chengguo-tech.com/backend/api/Article/getById?articleId=${params?.id}`
  // const res = await fetch(api, { method: "GET" })
  // const json: IArticleContent = await res.json()

  return {
    props: {
      commiteeDetail: {
        title: params?.id!
      }
    }
  }
}

const CommiteeDetail: NextPage<IProps> = ({ commiteeDetail }) => {
  const router = useRouter()
  const { id } = router.query

  return (
    <>
      <Head>
        <title>{commiteeDetail.title}</title>
        <meta name="description" content="Generated by VPMC" />
      </Head>

      <main className={style.container}>
        {commiteeDetail.title}
      </main>
    </>
  )
}

export default CommiteeDetail