import type { NextPage } from 'next'
import Router, { useRouter } from 'next/router'
import Head from 'next/head'
import style from './index.module.scss'
import CommiteeHeader from '../../../../components/CommiteeHeader'
import CommiteePhoto from '../../../../components/CommiteePhoto'
import WithNavFooterProtected from '../../../../layout/front-layout/WithNavFooterProtected'
import { ParsedUrlQuery } from 'querystring'
import { GetServerSideProps } from 'next'
import { ICommiteeAprDetail } from '../../../../store/slice/commitee'

export interface ITempCommiteeInfo {
  id: string
  date: string
  organization: string
  licenseYear: string
  licenseCode: string
  coordinate: string
  address: string
  license: string
}

interface IProps {
  commiteeDetail: ICommiteeAprDetail[]
  commiteeInfo: ITempCommiteeInfo
}

interface Params extends ParsedUrlQuery {
  id: string
}

export const getServerSideProps: GetServerSideProps<IProps, Params> = async ({
  params,
}) => {
  const headers = new Headers()
  let api = process.env.API_DOMAIN_PROD + `/api/Commitee/getAprInfo?commiteeId=${params?.id}`
  let res = await fetch(api, { method: "GET", headers: headers })
  const json: ICommiteeAprDetail[] = await res.json()

  api = process.env.API_DOMAIN_PROD + `/api/Commitee/getCommiteeInfoById?commiteeId=${params?.id}`
  res = await fetch(api, { method: "GET", headers: headers })
  const commiteeInfo = await res.json() as ITempCommiteeInfo
  return {
    props: {
      commiteeDetail: json,
      commiteeInfo: commiteeInfo
    }
  }
}

const CommiteeDetail: NextPage<IProps> = ({ commiteeDetail, commiteeInfo }) => {
  const router = useRouter()
  const { id } = router.query

  return (
    <>
      <Head>
        <title>VPMC | 實價登錄資訊平台</title>
        <meta name="description" content="Generated by VPMC" />
      </Head>

      <main className={style.container}>


        <CommiteePhoto />
        <CommiteeHeader
          commiteeDetail={commiteeDetail}
          commiteeInfo={commiteeInfo}
        />
      </main>
    </>
  )
}

export default WithNavFooterProtected(CommiteeDetail)