import type { NextPage } from 'next'
import { useRouter } from 'next/router'
import Head from 'next/head'
import { ParsedUrlQuery } from 'querystring'
import { GetServerSideProps } from 'next'
import dynamic from 'next/dynamic'
import Image from 'next/image'
import style from './index.module.scss'
import CommiteeHeader from '../../../../components/CommiteeHeader'
import CommiteePhoto from '../../../../components/CommiteePhoto'
import { ICommiteeAprDetail } from '../../../../store/slice/commitee'

interface IProps {
  commiteeDetail: ICommiteeAprDetail[]
}

interface Params extends ParsedUrlQuery {
  id: string
}

export const getServerSideProps: GetServerSideProps<IProps, Params> = async ({
  params,
}) => {
  const api = process.env.API_DOMAIN_PROD + `/api/Commitee/getAprInfo?commiteeId=${params?.id}`
  const res = await fetch(api, { method: "GET" })
  const json: ICommiteeAprDetail[] = await res.json()

  console.log(json)
  return {
    props: {
      commiteeDetail: json
    }
  }
}

const CommiteeDetail: NextPage<IProps> = ({ commiteeDetail }) => {
  const router = useRouter()
  const { id } = router.query

  return (
    <>
      <Head>
        <title>VPMC | 實價登錄資訊平台</title>
        <meta name="description" content="Generated by VPMC" />
      </Head>

      <main className={style.container}>


        <CommiteePhoto />
        <CommiteeHeader
          commiteeDetail={commiteeDetail}
        />
      </main>
    </>
  )
}

export default CommiteeDetail