import type { NextPage } from 'next'
import Head from 'next/head'
import style from '../styles/Home.module.scss'
import PageHeader from '../containers/PageHeader'
// import { applyBaseLayout } from '../layout'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>VPMC | 實價登錄資訊平台</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/yuantai.ico" />
      </Head>
      <main className={style.main}>
        <PageHeader
          title={'家，自由輕鬆找到'}
        />
      </main>
    </>
  )
}

export default Home
