import type { NextPage } from 'next'
import Head from 'next/head'
import style from '../styles/Home.module.scss'
import PageHeader from '../components/PageHeader'
import classNames from 'classnames'
import 'animate.css'
import WithNavFooter from '../layout/front-layout/WithNavFooter'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>VPMC | 實價登錄資訊平台</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/b.ico" />
      </Head>
      <main className={classNames({
        [style.main]: true,
        'animate__animated': true
      })}>
        <PageHeader
          title={'VPMC | 實價登錄資訊平台'}
        />
      </main>
    </>
  )
}

export default WithNavFooter(Home)
