import type { NextPage } from 'next'
import style from './index.module.scss'
import Drawer from '../../../components/Drawer'
import dynamic from 'next/dynamic'
import Head from 'next/head'

const RegionMapContainer = dynamic(
  () => import('../../../components/MapContainer/AprRegionMap'),
  { ssr: false }
)

const AprRegion: NextPage = () => {
  return (
    <>
      <Head>
        <title>VPMC | 實價登錄資訊平台</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/yuantai.ico" />
        <link rel="stylesheet" href="https://js.arcgis.com/4.23/@arcgis/core/assets/esri/themes/light/main.css" />

      </Head>
      <div className={style.main}>
        <Drawer
          open={true}
          onClose={() => { }}
        >
          {
            // commiteeInfo.commiteeInExtent.length !== 0
            //   ?
            //   commiteeInfo.commiteeInExtent.map((commitee, index) => {
            //     return <CommiteeCard key={index}
            //       {...commitee}
            //     />
            //   }) :
            //   <p>範圍內無社區，請放大地圖</p>
          }

        </Drawer>
        <div className={style.content}>

          <div className={style.mapContainer}>
            <RegionMapContainer basemap='gray' />
          </div>

        </div>
      </div>
    </>
  )
}

export default AprRegion
