import type { NextPage } from 'next'
import style from './index.module.scss'
import Drawer from '../../../components/Drawer'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import CountySelector from '../../../components/CountySelector'
import TownSelector from '../../../components/TownSelector'
import Image from 'next/image'

const RegionMapContainer = dynamic(
  () => import('../../../components/MapContainer/AprRegionMap'),
  { ssr: false }
)

const AprRegion: NextPage = () => {
  return (
    <>
      <Head>
        <title>VPMC | 實價登錄資訊平台</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/yuantai.ico" />
      </Head>
      <div className={style.main}>

        <div className={style.panel}>

          <div className={style.filterGroup}>
            <CountySelector />
            <TownSelector />
            <div className={style.searchBtn}>
              <Image src={'/aprRegion/search.png'} width='30px' height='30px' />
              <p>查詢</p>
            </div>
          </div>

          {/* <div className={style.graphGroup}>
          </div> */}

        </div>

        <div className={style.content}>

          <div className={style.mapContainer}>
            <RegionMapContainer basemap='gray' />
          </div>

        </div>
      </div>
    </>
  )
}

export default AprRegion
